# Generated by Django 3.2 on 2021-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20210709_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Out for delivery', 'Out for delivery'), ('Arrived', 'Arrived')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('appetizer', 'appetizer'), ('entree', 'entree'), ('dessert', 'dessert')], max_length=200, null=True),
        ),
    ]
