# Generated by Django 3.2 on 2021-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_auto_20210709_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(to='resturant.MenuItem'),
        ),
    ]
