# Generated by Django 3.2 on 2021-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_auto_20210709_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('full', 'full'), ('half', 'half')], max_length=50, null=True),
        ),
    ]
