# Generated by Django 3.2 on 2021-08-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0013_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
