# Generated by Django 3.2 on 2021-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0017_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultProfilePic.png', null=True, upload_to=''),
        ),
    ]
