# Generated by Django 3.2 on 2021-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0018_auto_20210804_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
