# Generated by Django 3.2 on 2021-08-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0019_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('fries', 'fries'), ('entree', 'entree'), ('dessert', 'dessert'), ('sauce', 'sauce')], max_length=200, null=True),
        ),
    ]
