# Generated by Django 3.2 on 2021-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0020_alter_menuitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_pic',
            field=models.ImageField(blank=True, default='solid-dark-grey-background.jpg', null=True, upload_to=''),
        ),
    ]
