# Generated by Django 3.2 on 2021-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0022_auto_20210810_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
