# Generated by Django 3.2 on 2021-08-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0023_order_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
