# Generated by Django 3.2 on 2021-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0025_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
