# Generated by Django 3.2 on 2021-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order In Progress', 'Order In Progress'), ('Order Confirmed', 'Order Confirmed'), ('Out for delivery', 'Out for delivery'), ('Arrived', 'Arrived')], max_length=200, null=True),
        ),
    ]
