# Generated by Django 3.2 on 2021-08-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0030_menuitem_fry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='fry_type',
            new_name='sauce_type',
        ),
    ]
